export const roleConfig = {
  manager: {
    title: 'Risk Manager Dashboard',
    description: 'Monitor vulnerabilities, generate mitigation plans, and track compliance.',
    icon: '📊',
    supabaseRole: 'RiskManager',
    color: '#007bff',
    colorLight: '#0056b3',
    price: 499,
    permissions: {
      canAssess: true,
      canExport: true,
      canEditStatus: true,
    },
  },
  operator: {
    title: 'Field Operator Dashboard',
    description: 'Scan perimeter threats using drone imagery and receive real-time alerts.',
    icon: '🛰️',
    supabaseRole: 'FieldOperator',
    color: '#fd7e14',
    colorLight: '#d96d0f',
    price: 199,
    permissions: {
      canAssess: true,
      canExport: false,
      canEditStatus: true,
    },
  },
  analyst: {
    title: 'Environmental Analyst Dashboard',
    description: 'Analyze flood zones, erosion risks, and meteorological threats.',
    icon: '🌍',
    supabaseRole: 'EnvironmentalAnalyst',
    color: '#28a745',
    colorLight: '#1e7e34',
    price: 299,
    permissions: {
      canAssess: true,
      canExport: false,
      canEditStatus: true,
    },
  },
  security: {
    title: 'IT Security Dashboard',
    description: 'Detect digital vulnerabilities and simulate breach scenarios.',
    icon: '🔐',
    supabaseRole: 'ITSecurityLead',
    color: '#dc3545',
    colorLight: '#b02a37',
    price: 399,
    permissions: {
      canAssess: true,
      canExport: true,
      canEditStatus: true,
    },
  },
  compliance: {
    title: 'Compliance Dashboard',
    description: 'Audit mitigation strategies and ensure regulatory alignment.',
    icon: '📁',
    supabaseRole: 'ComplianceOfficer',
    color: '#6c757d',
    colorLight: '#5a6268',
    price: 599,
    permissions: {
      canAssess: false,
      canExport: true,
      canEditStatus: false,
    },
  },
  intern: {
    title: 'Learning Dashboard',
    description: 'Practice with simulations and chat with AI DDRiVER anytime.',
    icon: '🎓',
    supabaseRole: 'Intern',
    color: '#17a2b8',
    colorLight: '#0f6f7e',
    price: 99,
    permissions: {
      canAssess: true,
      canExport: false,
      canEditStatus: true,
    },
  },
};
